### PR TITLE
Feature time frequency

### PR DESCRIPTION
**Pull request by martonvavrik**
STFT algorithm developed and integrated into flap, as detailed in #91

### CODE REVIEW

**Review by sandorzoletnik — CHANGES_REQUESTED** [review]
Please add calling method in data_object.py.
Please use the flap.config.merge_options() to set defaults

**Comment by sandorzoletnik** [comment]
Dear Marci,

You did not provide a test program for stft and a function for stft. Please observe that all operations (like apsd, cpds) have a method and a function. The method operates on a data object, the function on a data object in the storage. I have done this. I
have also created a mode in TESTDATA which generates a test signal with temporally changing frequency. I created a test_stft function in flap_tests.py. If you just run flap_tests it now tries to test stft with a signal with linearly changing frequency sine wave. I expect to see the temporally changing frequency peak, but I don't see anything. Please pull feature_time-frequency and test.

**Comment by martonvavrik** [comment]
Sorry, forgot to do it in the summer, but now that you mentioned, I'll check it out. (And also forgot to write the remaining tasks into the issue. Is there anything other in the to-do list in this issue?)

**Comment by sandorzoletnik** [comment]
Just check why flap_tests does not show what I expect. Maybe I did not use correct parameters, I used defaults.

**Comment by martonvavrik** [comment]
The STFT works fine, but the given signal's amplitude is around 0.015, and the resulting STFT's max amplitude is around 0.009. If you increase TESTDATA's amplitude (by 100x) it works fine. However we should still be able to plot STFT's with small values, so there might be an issue with the image plotter, because the lower limit for the plottable amplitude stays at 1.0.

**Pull request merged**
